### ISSUE TITLE
Sign up process not working 

### ISSUE THREAD

**Issue by xwshiba** [asciinema/asciinema-server#397] opened 2022-07-29 00:16 UTC
I am not receiving any emails when signing up. 
Checked my spam and it's not there.
Thought this might be an issue now?

**Comment by ardaguclu** [comment] 2022-07-29 10:15
Exact same thing also happened to me. I did not get any emails.

**Comment by hardest1** [comment] 2022-07-29 14:30
I have the same problem. Tried it with multiple different email addresses from different providers and had no success with any of them.
It looks like it is an issue on their end if we are all experiencing the same problem.

**Comment by sickill** [comment] 2022-08-03 18:24
Duplicate of #347

**Closed by sickill** 2022-08-03 18:24 UTC
